### ISSUE TITLE
Support io.js

### ISSUE THREAD

**Issue by RainbowDashDC** [crcn/nexe#105]
It'd be nice to have the ability to use either io.js or node.js

I'd like to implement this, but want to get others input.

**Comment by LorenzGardner** [comment]
They way we insert our stuff into the node project is fairly brittle. We simply look for a string match (in most cases something to do with the fs module as we know any version of node would have ref to that) and then sling our stuff in.

The part where nexe overrides all the command line arguments in particular is fairly unstable, and will if it doesn't already need work for the latest versions of node.js

Io.js changes faster. That is the whole reason behind the fork. Obviously that comes with good things, but the monkey patching is a lot more likely to start needing version specific patching. Combined with the fact that you need to be able to monkey patch two diff projects and I think we may need to discuss better ways of getting into the project build.

I don't know what that better way would be.

This is all a bit of  tangent however, and of course there is no good reason to not add support for io.js if there is going to be someone around to maintain it.

**Comment by RainbowDashDC** [comment]
I'll look into how hard it is currently and look at how much work has been done over relevant monkey patched areas to see how likely we can estimate it would be changed.

**Comment by RainbowDashDC** [comment]
Currently have iojs working in iojs branch.

**Comment by RainbowDashDC** [comment]
Done by #108!
