### ISSUE TITLE
Absolute paths wonky for temp dir

### ISSUE THREAD

**Issue by wavded** [crcn/nexe#107]
e.g. say I run the following in `/path/to/dir`

```sh
nexe -i index.js -o dist/proxy -t $TMPDIR -r 0.10.37
```

where `$TMPDIR` is `/tmp` in this case.  it actually builds everything at `/path/to/dir/tmp` instead of `/tmp`.

**Comment by RainbowDashDC** [comment]
Huh. That's odd. Let me see if I can reproduce.

**Comment by wavded** [comment]
If it helps, I'm was running io.js 1.5.1 and was on OSX when I noticed the behavior.

**Comment by RainbowDashDC** [comment]
Could you try the branch iojs and tell me if it fixes anything? It has some misc changes that may help

**Comment by RainbowDashDC** [comment]
Confirmed, will submit a patch to iojs and then merge it with the support of iojs that is coming soon.

**Comment by RainbowDashDC** [comment]
exe.js:175:_downloadNode

```
var nodeFileDir = path.resolve(path.join(process.cwd(), directory, version));
```

That's your problem right there, well our problem. It's combining process.cwd with the directory

**Comment by wavded** [comment]
Thanks for looking into it @RainbowDashDC, any eta on the iojs release?

**Comment by RainbowDashDC** [comment]
Hopefully today!
