### ISSUE TITLE
Simple compile 

### ISSUE THREAD

**Issue by IGRACH** [crcn/nexe#117]
Hi I'm truing to make simple .bin file with this module. My file test.js:

    console.log('test');

And I'm running whit this command: `nexe -i  test.js -o test.bin`
I'm getting this error:

     Build skipped. To build, this file needs to run from VS cmd prompt.
     ----> cp C:\tmp\nexe\nodejs\0.10.35\node-v0.10.35\Release\node.exe C:\Users\Bane\testjs\test.bin
     ....> ERROR: Couldn't copy binary.
    
I'm running it on win7/64bit. Do I need Visual Studio(VS) for this or what?

**Comment by RainbowDashDC** [comment]
Yes you need Visual Studio in order too compile it. 

> Visual Studio 2010 or 2012

**Comment by jaredallard** [comment]
Closing, if you have any more issues please bring them up!
