### ISSUE TITLE
Update the ReadMe to clarify Windows pre-reqs

### ISSUE THREAD

**Issue by kasajian** [crcn/nexe#119]
The readme currently talks about requiring python and visual studio for Windows.   It's referring to what is needed by the developer to use nexe.   However, some people are assuming it means the final executable requires those things to be installed.   Please  update the readme to clarify

**Comment by RainbowDashDC** [comment]
Hm. Never saw it that way. I'll clarify it.

**Comment by jaredallard** [comment]
should be resolved by 686f67f
