### ISSUE TITLE
bad option: --child_process

### ISSUE THREAD

**Issue by yuzhigang33** [crcn/nexe#123]
I get the latest commit version, not npm.
when i run the example, I get the following info but no other error or warning. the example code is running ok.

```
/Users/yzg/github/nexe/examples/hello-world/hello-world: bad option: --child_process
```

**Comment by jaredallard** [comment]
Currently npm & master are the same. I just release 0.4.0 today. I'm a tad bit busy at the moment, and I believe this has already been reported. I'm looking into it.

Thanks for the report! :) Try 0.3.9 and see if it helps.

**Comment by yuzhigang33** [comment]
ok, thanks.
I use the npm package just now. it's ok.^_^。
