### ISSUE TITLE
parsing command arguments issue

### ISSUE THREAD

**Issue by ttchoi** [crcn/nexe#39]
i'm trying to compile my command tools in single binary file by following command

nexe -i cci.js -o cci.o

everything is good, except the arguments pass from command console.

[root@host ssh.js]# ./cci.o -m cmd.ls -k '*' // error
Error: unrecognized flag -m
Try --help for options
cci : version 0.7.0

Options:
  -m, --method         Mangerment console
                       [ cmd.(ls/add/get/mod/del/man/chgrp/edit/exec) ]
                       [ file.(ls/add/get/mod/del/man/chgrp) ]
  -k, --key            Key for mangerment console
  -f, --file           source file for script or file method
  --desc, --desc       comment for script
  --name, --name       specified with new scrip

[root@host ssh.js]# ./cci.o "any of string" -m cmd.ls -k '*'  // this one run correct
xj/cci                      | 2014-01-07 02:42:35 | 52.8K | added at 2014-01-07 23:48:23
xj/ec-swapdetect            | 2014-01-07 20:50:12 | 0.05K | added at 2014-01-07 23:42:59
xj/cci.js                   | 2014-01-07 02:34:09 | 52.5K | added at 2014-01-07 02:30:29
xj/tlog                     | 2014-01-07 02:34:26 | 0.06K | find latest log
xj/create_swap_partition.sh | 2014-01-07 21:29:55 | 0.49K | added at 2014-01-07 23:42:13
users/ssh.js                | 2014-01-07 02:32:48 | 37.1K | ssh batch nodejs script
users/xj.int.sh             | 2014-01-07 02:33:27 | 0.15K | it's test interactive script
users/hiconfig.sh           | 2014-01-07 02:33:40 |  3.3K | hiconfig

**Comment by RainbowDashDC** [comment]
Fixed by #44 and is currently avilable in `0.3.4`+ and possibly lower version.
