### ISSUE TITLE
Overzealous require() substitutions

### ISSUE THREAD

**Issue by mappu** [crcn/nexe#59]
Hi, there is a problem with string substitutions being overzealously applied in `nexe`. 

Example 1:

`var fs = require('fs'); var http = require('http');` becomes `var fs = require('myapp.js'); var http = require('myapp.js');` which is just wrong.

Example 2:

Also later on, using "fs" or "http" as string constants also become erroneously replaced, e.g. `if (protocol_used = "http")` becomes `if (protocol_used = "myapp.js")` . This is quite bad. The replacements should err on the side of missing replacements rather than blindly every single usage of the string.

This is causing any project that depends on node fs/http libraries to fail (and i assume the problem exists with other builtin libraries)

**Comment by LorenzGardner** [comment]
This should be marked as fixed.
