### ISSUE TITLE
No complication step?

### ISSUE THREAD

**Issue by greggman** [crcn/nexe#60]
Before I go try to add this feature I thought I'd ask.

Why even have a complication step? I'm fine if my node app runs uncompiled. All I want is  some kind of installable executable that has all my apps files installed in some folder and then runs the version of node embedded in those files with the right command.

Is that a feature/option that would be good for nexe? Something like `--no-compile`

**Comment by RainbowDashDC** [comment]
I'm going to go ahead and say this is not currently on the roadmap, so I'm going to add a `wontfix` label because I don't see a point to this flag, but anyone is free to implement it.

**Comment by greggman** [comment]
So FYI, I ended up making my own thing. I haven't made it generic yet but if you want something to hack on it's here

http://github.com/greggman/hft-exe/ 

That script currently takes [happyfuntimes](http://github.com/happyfuntimes/) and builds an executable and installer. It requires a Windows machine to make a windows version and an OSX machine to make an OSX version but it does work. It's currently hard coded to make happyfuntimes but it would be easy to make it more generic. Maybe I'll work on that tonight.
