### ISSUE TITLE
Cross-platform service

### ISSUE THREAD

**Issue by majimboo** [crcn/nexe#62]
I had a question on [stackoverflow](http://stackoverflow.com/questions/24796352/writing-a-cross-platform-background-service), could this be a solution to that?

Anyways, when you say "native modules" aren't supported, what are native module? Is it the modules in npm? or the modules that needs to be build with gyp?

I plan to use `chokidar` for the directory watching. Is that considered a native module or is it supported? Considering its only a wrapper of `fs.watch` without any external dependency.

And by service I mean that there won't be any GUI. I just want to install it along with my application which is the actual GUI and I use nodewebkit for that.

But I want to separate the service from the application. I also want to execute it and run it on system start up for mac/win.

**Comment by RainbowDashDC** [comment]
This is more of a programmatic question-- which is fine. Marking this as closed because you seem to have gotten all the help that is oriented towards nexe can provide.
