### ISSUE TITLE
Compiling error caused by non-ascii value

### ISSUE THREAD

**Issue by Vimos** [crcn/nexe#63]
non-ascii value lib/nexe.js:235:9
make[1]: *** [/home/vimos/Public/git/oct_suggestion/build/matchn/tmp/nexe/latest/node-v0.10.29/out/Release/obj/gen/node_natives.h] Error 1
make[1]: Leaving directory `/home/vimos/Public/git/oct_suggestion/build/matchn/tmp/nexe/latest/node-v0.10.29/out'
make: *** [node] Error 2

At line 235 of nexe.js
  data1 = {
    w: "激荡三十年",
some non-ascii exists.

How can I solve this if I need these non-ascii?

**Comment by RainbowDashDC** [comment]
Fixed by #79 and is currently available in `0.3.x` as stated by @crcn
