### ISSUE TITLE
nexe does not support recursive/circular module dependencies

### ISSUE THREAD

**Issue by mikaelhm** [crcn/nexe#64]
I know that recursive/circular dependencies are not desirable, however there are modules out there that uses it. (Like https://github.com/sjkaliski/numbers.js)

If you have any circular dependency you will get this error when you try to run it:

```
nexe.js:5
        var module = {
        ^
RangeError: Maximum call stack size exceeded
```

**Comment by LorenzGardner** [comment]
This was indeed fixed when dumping sardines for make-deps. circular deps now work
