### ISSUE TITLE
the required module taken as a folder when compilling nexe 0.3.1

### ISSUE THREAD

**Issue by williamthe** [crcn/nexe#68]
var express = require('express')
, routes = require('./routes')
, http = require('http')
, path = require('path')
, connect = require('connect');

C:\Users\william\Desktop\Chat-Application>nexe -i ./app.js -o app.exe
----> bundle C:\Users\william\Desktop\Chat-Application\app.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'C:\Users\william\Desktop\Chat-Application\path'

how to solve this?

**Comment by RainbowDashDC** [comment]
This was fixed, per the inital report. If you have any other issues then please create a new issue report. Thanks!
