### ISSUE TITLE
Problem compiling - ENOENT, open 'sys'

### ISSUE THREAD

**Issue by ding444** [crcn/nexe#71]
Here's what I'm getting when I try to compile: 

    ----> downloading http://nodejs.org/dist/node-latest.tar.gz
    [================================================================================]
    ----> tar -xf /Users/ding/Desktop/craigslist_daemon/tmp/nexe/latest/node-latest.tar.gz -C /Users/ding/Desktop/craigslist_daemon/tmp/nexe/latest
    ----> bundle /Users/ding/Desktop/craigslist_daemon/search_craigslist
    
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: ENOENT, open 'sys'

System is OSX

**Comment by CKarper** [comment]
I can repro this.   This is due to resolve looking at require statements that will never execute.  Any modules that still refer to the util lib as sys, even in a catch statement, will cause this error.   

See [redis](https://github.com/mranney/node_redis) for one example

**Comment by CKarper** [comment]
This still exists after b040337, as it's an ENOENT, not just an emitted 'missing'.
