### ISSUE TITLE
lib/bundle.js — require has problem with parsing modules key, affects Windows executables (TypeError: undefined is not a function)

### ISSUE THREAD

**Issue by mrauhu** [crcn/nexe#80]
# Bugs affects exe-compilation on Windows

* Not escaped slashes: 'C:\test-nexe' -> 'C: est-exe' (not 'C:\\test-nexe' -> 'C:\test-exe')
* Not working require for windows path

## Where bugs may be hiding

Need JSON.stringify():
https://github.com/crcn/nexe/blob/ff09ef6755d2b06d6b57e5d8caf9982ed391b866/lib/bundle.js#L91
```
dbuffer.push("'" + dep.id + "'
                     ^
```

Problem with require:
https://github.com/crcn/nexe/blob/ff09ef6755d2b06d6b57e5d8caf9982ed391b866/lib/bundle.js#L41
https://github.com/crcn/nexe/blob/ff09ef6755d2b06d6b57e5d8caf9982ed391b866/lib/bundle.js#L112

## How to reproduce

Install nexe
```
C:\> npm install -g nexe
```

Create test project:
```
C:\> mkdir test-nexe
C:\> cd test-nexe
C:\test-nexe> npm install mkdirp
```

Create app.js
```
var mkdirp = require('mkdirp');
var dir = 'test';
mkdirp( dir, function (err) {
  if (err) {
    console.error(err);
  } else {
    console.log('created directory: ' + dir );
  }
});

```

Run app.js
```
C:\test-nexe> node app.js
```
output:
```
created directory: test
```

Compile app.js to exe
```
C:\test-nexe> nexe -i app.js -o app.exe
```

Run app.exe
```
C:\test-nexe> app.exe
```
output:
```
nexe.js:32
mkdirp( dir, function (err) {
^
TypeError: undefined is not a function
    at Array.call.C:test-nexeapp.js.mkdirp [as 0] (nexe.js:32:1)
    at initModule (nexe.js:13:11)
    at Array.forEach (native)
    at nexe.js:22:8
    at nexe.js:29:4
    at NativeModule.compile (node.js:900:5)
    at Function.NativeModule.require (node.js:869:18)
    at Function.Module._load (module.js:297:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by RainbowDashDC** [comment]
As @LorenzGardner said, it's in the main branch so marking this closed. Great quality bug report though!
