### ISSUE TITLE
Add python flag for environments where 2.7 is not default

### ISSUE THREAD

**Issue by rhinoceraptor** [crcn/nexe#94]
npm implements this feature like this:

```npm install foo --python=/path/to/python```.

**Comment by RainbowDashDC** [comment]
Looking into this further this will be harder to implment, but not impossible, because node.js's build process is what requires python, I will most likely have to settle with editing the build file. Which isn't the end of the world.

Anyways, I'm working on it. Just a status update.

**Comment by rhinoceraptor** [comment]
Cool, thanks!
