### ISSUE TITLE
Fatal error on missing required files, even when they're not actually required...

### ISSUE THREAD

**Issue by CKarper** [crcn/nexe#97]
Error: Cannot find module './mongo' from '/MyApp/node_modules/mongoose/node_modules/mquery/lib/collection'

So, resolve is choking on this beaut of a structure from [mquery](https://github.com/aheckmann/mquery)
```javascript
module.exports =
  env.isNode ? require('./node') :
  env.isMongo ? require('./mongo') :
  require('./browser');
```

Yes, that *is* a nested ternary operation...    *gak*    

Anyway, this lib apparently only includes `node.js` in the npm package.   The others are never called, and thus don't hurt anything by not being there, but resolve finds them and chokes.  

This means that nexe can't package any apps using [mongoose](https://github.com/LearnBoost/mongoose).   That's a problem.

Can we make some failures not critical, or find some way of passing libs to ignore?

Related: #71

**Comment by RainbowDashDC** [comment]
I suppose we could make it so that it throws a warning whenever a required file is not found.

**Comment by RainbowDashDC** [comment]
This has been fixed by a soon to be pushed commit. just making sure it builds properly.
