### ISSUE TITLE
Implement same-line progress bar on win32

### ISSUE THREAD

**Issue by RainbowDashDC** [crcn/nexe#98]

**Comment by CKarper** [comment]
What is this?   Just curious.

**Comment by RainbowDashDC** [comment]
When downloading node on windows the progress bar updates on a newline on each "=" added. Unline on *nix systems.

**Comment by CKarper** [comment]
Aaah, gotcha.   Thanks. :-)

**Comment by RainbowDashDC** [comment]
It seems to be `process.stdout.colums` giving an (incorrect?) vaule too npm `progress`'s width option.
